# Generated by Django 4.1.7 on 2023-03-01 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoList",
            new_name="TodoLists",
        ),
    ]
